#!/bin/bash
# Refreshes this mirror from the working copies in ~/Developer.
#
# Copies source only: build output is regenerated by each build.sh, and the
# whisper model must never enter the repo. Deletes files that have gone from the
# source, so a rename in ~/Developer does not leave a ghost here.
set -euo pipefail
cd "$(dirname "$0")"

for app in CodingAgentUsage Deadlines Jot PaperNotes Pomodoro VoiceBridge; do
  src="$HOME/Developer/$app"
  [ -d "$src" ] || { echo "skipping $app — not in ~/Developer"; continue; }
  rsync -a --delete \
        --exclude '.git' --exclude '.build' --exclude '/build' --exclude '.DS_Store' \
        --exclude '*.o' --exclude '*.pcm' --exclude '*.swiftmodule' \
        --exclude 'DerivedData' --exclude 'models' --exclude '*.iconset' \
        "$src/" "./$app/"
  echo "synced $app"
done

git status --short
